### ISSUE TITLE
Questions about trackers in CASSYS

### ISSUE THREAD

**Issue by spelland74** [CanadianSolar/CASSYS#1]
Hello,

I just downloaded CASSYS. Thanks for making this tool, and the underlying code, available. Two questions about trackers:
-Is it possible to include backtracking?
-Is it possible to calculate array self-shading for tracking systems?

If these features aren't yet available, any plans on incorporating them?
Best regards,
Sophie

**Comment by abhijeetpai** [comment]
Hello Sophie, 

Thank you for your e-mail. 

These features are not available yet, but we are currently in the process of adding backtracking to the systems. Once this has been tested thoroughly, we will focus on calculating array self-shading for these systems. 

Our best estimate is to complete these in the next two-three weeks, but we will keep you posted on our progress.

Best Regards,
Abhijeet

**Comment by spelland74** [comment]
Hello Abhijeet,

Thanks for your quick reply, and for keeping me posted. Much appreciated!

Best regards,
Sophie

**Comment by abhijeetpai** [comment]
Hello Sophie,

These features are now included and the interface will notify you of situations where the shading is not available. 

Thank you very much for your e-mail.

Best Regards,
Abhijeet
