### ISSUE TITLE
Rsh,base Calculation

### ISSUE THREAD

**Issue by mibu9938** [CanadianSolar/CASSYS#2]
Nice tool, thanks for sharing.

I think you have a sign error in your Rsh,base calculation (equation 9 in the User Guide). It should be:
Rsh,base = Rsh,ref - Rsh0*exp(-Rsh,exp)/(1-exp(-Rsh,exp))

Apologies if I am interpreting this incorrectly. My source is:
K. Sauer, T. Roessler, C. W. Hansen, Modeling the Irradiance and Temperature Dependence of Photovoltaic Modules in PVsyst, IEEE Journal of Photovoltaics v5(1), January 2015.

Thanks,
Michelle Burns

**Comment by abhijeetpai** [comment]
Hello Michelle,

Thank you for informing us of the error in the Physical Models Guide. 
We will resolve the issue in our next update, and close the ticket accordingly. 

Thank you very much.

Regards,
Abhijeet Pai

**Comment by abhijeetpai** [comment]
The error has been resolved in the physical models guide. 

Thank you very much once again for reporting the issue.
